spring:
  session:
    store-type: jdbc
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
  jpa:
    hibernate:
      ddl-auto: create-drop
